# Generated by Django 5.2 on 2025-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('FF', 'Fast Food'), ('OT', 'Others')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
